"""Public API for the Content Skills Framework."""

from .contracts import load_schema, validate_metadata_dict, validate_result_dict, validate_schema_documents
from .errors import (
    CapabilityDeniedError,
    CircuitOpenError,
    ContractError,
    ExecutionTimeoutError,
    FrameworkError,
    InvalidRequestError,
    InvalidResultError,
    ProviderUnavailableError,
    QuotaExceededError,
    ToolConflictError,
    ToolNotFoundError,
    WorkerCrashedError,
)
from .models import (
    CONTRACT_VERSION,
    Capability,
    ExecutionPlan,
    ExecutionRequest,
    ExecutionResult,
    ExecutionStep,
    LLMProviderConfig,
    NormalizedRequest,
    Status,
    ToolCandidate,
    ToolMetadata,
    ToolSelection,
)
from .persistent_index import (
    ENTRY_POINT_GROUP,
    IndexedTool,
    discover_external_entry_points,
    ensure_index,
    environment_fingerprint,
    index_is_current,
    list_index,
    lookup,
    rebuild_index,
)

__version__ = "0.2.0"

__all__ = [
    "CONTRACT_VERSION",
    "Capability",
    "ExecutionPlan",
    "ExecutionRequest",
    "ExecutionResult",
    "ExecutionStep",
    "LLMProviderConfig",
    "NormalizedRequest",
    "Status",
    "ToolCandidate",
    "ToolMetadata",
    "ToolSelection",
    "ENTRY_POINT_GROUP",
    "IndexedTool",
    "discover_external_entry_points",
    "ensure_index",
    "environment_fingerprint",
    "index_is_current",
    "list_index",
    "lookup",
    "rebuild_index",
    "load_schema",
    "validate_metadata_dict",
    "validate_result_dict",
    "validate_schema_documents",
    "FrameworkError",
    "ContractError",
    "InvalidRequestError",
    "InvalidResultError",
    "ToolNotFoundError",
    "ToolConflictError",
    "CapabilityDeniedError",
    "ProviderUnavailableError",
    "ExecutionTimeoutError",
    "QuotaExceededError",
    "CircuitOpenError",
    "WorkerCrashedError",
]
