"""Public API for the Content Skills Framework."""

from .contracts import load_schema, validate_metadata_dict, validate_result_dict, validate_schema_documents
from .cache import CacheStats, ToolCache
from .errors import (
    CapabilityDeniedError,
    CircuitOpenError,
    ContractError,
    ExecutionTimeoutError,
    FrameworkError,
    InvalidRequestError,
    InvalidResultError,
    ProviderUnavailableError,
    QuotaExceededError,
    ToolConflictError,
    ToolNotFoundError,
    WorkerCrashedError,
)
from .models import (
    CONTRACT_VERSION,
    Capability,
    ExecutionPlan,
    ExecutionRequest,
    ExecutionResult,
    ExecutionStep,
    LLMProviderConfig,
    NormalizedRequest,
    Status,
    ToolCandidate,
    ToolMetadata,
    ToolSelection,
)
from .persistent_index import (
    ENTRY_POINT_GROUP,
    IndexedTool,
    discover_external_entry_points,
    ensure_index,
    environment_fingerprint,
    index_is_current,
    list_index,
    lookup,
    rebuild_index,
)
from .phases import (
    PHASE_DESCRIPTORS,
    PHASE_ENTRY_POINT_GROUP,
    PhaseDescriptor,
    ResourceProfile,
    discover_phase_entry_points,
    get_phase,
    list_phases,
    tools_for_phase,
)
from .router import DeterministicRouter, RequestNormalizer, RouteDecision
from .llm import LLMCallStats, StructuredLLMProvider, TOOL_SELECTION_SCHEMA
from .sandbox import POLICIES, SandboxPolicy, get_policy, safe_environment
from .supervisor import SupervisedExecution, Supervisor
from .quotas import QuotaLease, QuotaManager, QuotaPolicy, QuotaSnapshot
from .circuit_breaker import CircuitBreakerManager, CircuitPermit, CircuitPolicy, CircuitSnapshot, CircuitState

__version__ = "0.2.0"

__all__ = [
    "CONTRACT_VERSION",
    "CacheStats",
    "Capability",
    "ExecutionPlan",
    "ExecutionRequest",
    "ExecutionResult",
    "ExecutionStep",
    "LLMProviderConfig",
    "NormalizedRequest",
    "Status",
    "ToolCandidate",
    "ToolMetadata",
    "ToolSelection",
    "ToolCache",
    "ENTRY_POINT_GROUP",
    "IndexedTool",
    "discover_external_entry_points",
    "ensure_index",
    "environment_fingerprint",
    "index_is_current",
    "list_index",
    "lookup",
    "rebuild_index",
    "PHASE_DESCRIPTORS",
    "PHASE_ENTRY_POINT_GROUP",
    "PhaseDescriptor",
    "ResourceProfile",
    "discover_phase_entry_points",
    "get_phase",
    "list_phases",
    "tools_for_phase",
    "DeterministicRouter",
    "RequestNormalizer",
    "RouteDecision",
    "LLMCallStats",
    "StructuredLLMProvider",
    "TOOL_SELECTION_SCHEMA",
    "POLICIES",
    "SandboxPolicy",
    "get_policy",
    "safe_environment",
    "SupervisedExecution",
    "Supervisor",
    "QuotaLease",
    "QuotaManager",
    "QuotaPolicy",
    "QuotaSnapshot",
    "CircuitBreakerManager",
    "CircuitPermit",
    "CircuitPolicy",
    "CircuitSnapshot",
    "CircuitState",
    "load_schema",
    "validate_metadata_dict",
    "validate_result_dict",
    "validate_schema_documents",
    "FrameworkError",
    "ContractError",
    "InvalidRequestError",
    "InvalidResultError",
    "ToolNotFoundError",
    "ToolConflictError",
    "CapabilityDeniedError",
    "ProviderUnavailableError",
    "ExecutionTimeoutError",
    "QuotaExceededError",
    "CircuitOpenError",
    "WorkerCrashedError",
]
